### ISSUE TITLE
libxmp discovery fails if libxmp is a static-only and libm-dependent build

### ISSUE THREAD

**Issue by sezero** [libxmp/xmp-cli#36]
As the title says.

One solution might be re-trying in configure with `-lm` added to `LIBS`.
Comments?

**Comment by AliceLR** [comment]
I'm not familiar with how other libraries usually do this (could go the libpng/SDL route and make a `libxmp-config`, I guess...), but retrying `-lxmp` detection with `-lm` is probably OK.

**Comment by sezero** [comment]
> I'm not familiar with how other libraries usually do this (could go the libpng/SDL route and make a `libxmp-config`, I guess...),

We already have `libxmp.pc` (the pkg-config file), but the default method of using
it only uses its `Libs:` field.

> but retrying `-lxmp` detection with `-lm` is probably OK.

Will try cooking up something
